name: Callbacks Module
# This workflow runs when a PR is opened that targets code that is part of the callbacks module.
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: v1.54.2
          args: --timeout 5m
          working-directory: modules/apps/callbacks

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TODO: builds for arm and arm64 are currently failing after we added the
        # docker build.
#        go-arch: ['amd64', 'arm', 'arm64']
        go-arch: ['amd64']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build callbacks-module
        run: docker build . -f modules/apps/callbacks/Dockerfile --build-arg GOARCH=${{ matrix.go-arch }}


  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Go Test
        run: |
          cd modules/apps/callbacks
          go test -v -mod=readonly ./...
