---
name: Capability Module
on:
  push:
    branches: [main]
  pull_request:
    paths:
      - './modules/capability'
      - './.github/workflows/capability.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-arch: ["amd64", "arm", "arm64"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Build capability-module
        run: |
          cd modules/capability
          GOARCH=${{ matrix.go-arch }} go build ./...

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Go Test
        run: |
          cd modules/capability
          go test -mod=readonly ./...
