name: "Delete old images"
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # runs every week on Sunday

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  delete-images:
    runs-on: ubuntu-latest
    steps:
      - name: "delete images"
        run: |
          gh api -X GET /orgs/cosmos/packages/container/ibc-go-simd/versions | jq
