name: "Delete old images"
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # runs every week on Sunday

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  delete-images:
    runs-on: ubuntu-latest
    outputs:
      versions-to-delete: ${{ steps.fetch-all-images.outputs.versions-to-delete }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: "Fetch images"
        id: fetch-all-images
        run: echo "::set-output name=versions-to-delete::$(gh api -X GET /orgs/cosmos/packages/container/ibc-go-simd/versions)"
      - name: "Get images to delete"
        run: go run cmd/get_image_versions_to_delete/main.go "${{ steps.fetch-all-images.outputs.versions-to-delete }}"
