name: Check Markdown Links
on:
  pull_request:
    paths:
      - "**.md"
      - "!.github/**"
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          # Check all markdown and html files in repo (default)
          args: --verbose --no-progress './**/*.md'
          fail: true
