name: Backwards Compatibility Tests
on:
  workflow_dispatch:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run "e2e-manual-simd.yaml" -f chain-a-tag="main" -f chain-b-tag="main" -f test-entry-point="TestTransferTestSuite"

